config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates:
      branch: main
      repo: https://gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Sty:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-sepia-snail.sh
        container: qc.sty_sunny-auburn-greyhound
timeout: 5400
