config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates:
      branch: main
      repo: https://gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-salmon-anteater.sh
        container: qc.acc_dorky-seashell-capuchin
  QC.Doc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cobalt-mastiff.sh
        container: qc.doc_lousy-cerise-quoll
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-emerald-wolverine.sh
        container: qc.doc_shaky-orchid-cow
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-gamboge-capuchin.sh
        container: qc.doc_flabby-gamboge-swan
  QC.Lic:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-apricot-cow.sh
        container: qc.lic_whiny-peach-dhole
  QC.Sty:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-platinum-uguisu.sh
        container: qc.sty_dorky-cyan-moorhen
  QC.Ver:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-coral-beetle.sh
        container: qc.ver_wiggy-ultramarine-dane
timeout: 5400
